defaults:
  - train: robobrain_x0
  - _self_

experiment:
  exp_name: robobrain_x0
  exp_dir: ./${experiment.exp_name}
  task:
    type: train
    backend: megatron
    entrypoint: ./flagscale/train/megatron/train_robobrain_x0.py

  runner:
    nnodes: 1
    nproc_per_node: 4
    rdzv_backend: static
    # hostfile: /share/project/jiyuheng/exp0/hostfile.32
    # ssh_port: 22
  cmds:
    before_start: ulimit -n 1048576 && source /root/miniconda3/bin/activate flagscale-train
  envs:
    CUDA_VISIBLE_DEVICES: 3,4,5,6
    CUDA_DEVICE_MAX_CONNECTIONS: 1
    NVTE_APPLY_QK_LAYER_SCALING: 0
    NVTE_ALLOW_NONDETERMINISTIC_ALGO: 0
    NCCL_IB_DISABLE: 0
    NCCL_IB_HCA: mlx5_104,mlx5_105,mlx5_106,mlx5_107
    GLOO_SOCKET_IFNAME: ens101
    NCCL_SOCKET_IFNAME: ens101
    NCCL_IB_GID_INDEX: 7

action: run

hydra:
  run:
    dir: ${experiment.exp_dir}/hydra
